- name: Additional facts
  ansible.builtin.include_tasks:
    ../../configuration/tasks/gathering-facts.yaml

- name: Default vars
  ansible.builtin.include_vars:
    ../../configuration/vars/default.yaml

- name: Prometheus
  ansible.builtin.include_tasks:
    ./prometheus-alertmanager.yaml



