---

# Deploy Prometheus Alertmanager
- block:

  # If firewall is running open the needed port.
  - name: Prometheus Alertmanager - Firewall add port while online
    ansible.posix.firewalld:
      port: "{{prometheus_alertmanager_port}}/tcp"
      permanent: true
      state: enabled
      immediate: true
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state == "running"

  - name: Prometheus Alertmanager - Install package
    community.general.zypper:
      name: golang-github-prometheus-alertmanager
      state: latest


  - name: Prometheus Alertmanager - Create config file
    ansible.builtin.template:
      src: alertmanager.yml
      dest: /etc/prometheus/alertmanager.yml
      mode: "0644"
    register: alertmanager_conf  

  - name: Prometheus Alertmanager - Create sysconfig file
    ansible.builtin.template:
      src: sysconfig-prometheus-alertmanager
      dest: /etc/sysconfig/prometheus-alertmanager
      mode: "0644"
    register: alertmanager_sysconfig_conf  


  - name: Prometheus Alertmanager - Restart service
    ansible.builtin.service:
      name: prometheus-alertmanager.service
      enabled: true
      state: restarted
    when:
      - alertmanager_conf.changed or alertmanager_sysconfig_conf.changed or
        ansible_facts.services["prometheus-alertmanager.service"].state != "running"

  when:  deploy_prometheus_alertmanager and (groups['prometheus_alertmanager'] | length  == 1)



# Don't deploy Prometheus Alertmanager, stop service and disable port 
- block:

  - name: Prometheus Alertmanager - Remove package
    community.general.zypper:
      name: golang-github-prometheus-alertmanager
      state: absent

  - name: Prometheus Alertmanager - Remove config files 
    ansible.builtin.file:
      path: /etc/prometheus/alertmanager.yml
      state: absent
    when: cleanup_config 

  - name: Prometheus Alertmanager - Remove sysconfig files 
    ansible.builtin.file:
      path: /etc/sysconfig/prometheus-alertmanager
      state: absent
    when: cleanup_config 

  # If firewall is not running but installed we have to disable the ports without "immediate:".
  - name:  Prometheus Alertmanager - Firewall remove port while offline
    ansible.posix.firewalld:
      port: "{{prometheus_alertmanager_port}}/tcp"
      permanent: true
      offline: true
      state: disabled
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state != "running"

  # If firewall is running "immediate:" will be used to disable the port immediately.
  - name: Prometheus Alertmanager - Firewall remove port while online
    ansible.posix.firewalld:
      port: "{{prometheus_alertmanager_port}}/tcp"
      permanent: true
      immediate: true
      state: disabled
    when:
      - ansible_facts.services["firewalld.service"].state == "running"


  when: not deploy_prometheus_alertmanager or (groups['prometheus_alertmanager'] | length  == 0)    