{
 "title": "Example Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(inventory_hostname)"
    }
   },
   { "name": "cpu", "label": "CPU", "query": { "query": "label_values(cpu)" } },
   { "name": "filter", "label": "Log Filter:" }
  ]
 },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{inventory_hostname=\"$host\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{inventory_hostname=\"$host\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{inventory_hostname=\"$host\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{inventory_hostname=\"$host\", cpu=~\"$cpu\", mode=\"idle\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} {{mode}}"
    },
    {
     "expr": "rate(node_cpu_seconds_total{inventory_hostname=\"$host\", cpu=~\"$cpu\", mode=\"iowait\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} {{mode}}"
    },
    {
     "expr": "rate(node_cpu_seconds_total{inventory_hostname=\"$host\", cpu=~\"$cpu\", mode=\"user\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} {{mode}}"
    },
    {
     "expr": "rate(node_cpu_seconds_total{inventory_hostname=\"$host\", cpu=~\"$cpu\", mode=\"system\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} {{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{inventory_hostname=\"$host\"}",
     "legendFormat": "MemTotal"
    },
    {
     "expr": "node_memory_MemTotal_bytes{inventory_hostname=\"$host\"} - node_memory_MemFree_bytes{inventory_hostname=\"$host\"}",
     "legendFormat": "MemUsed"
    }
   ]
  },
  {
   "title": "Dirty Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{inventory_hostname=\"$host\"}",
     "legendFormat": "Dirty Bytes"
    }
   ]
  },
  { "title": "Loki Syslog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "barchart",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"systemd-journal\", inventory_hostname=\"$host\"} |= `$filter` [$__interval])"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", inventory_hostname=\"$host\"} |= `$filter`"
    }
   ]
  }
 ]
}