{
 "title": "Example Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(instance)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_time_seconds * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Net RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(collectd_interface_if_packets_rx_total{instance=~\"$host.*\", interface!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "DIsk root filesystem",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$host.*\",mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"$host.*\",mountpoint=\"/\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$host.*\",mountpoint=\"/\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Load ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\nnode_load1{instance=~\"$host.*\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{instance=~\"$host.*\"}",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{instance=~\"$host.*\"}",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "Net TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(collectd_interface_if_packets_tx_total{instance=~\"$host.*\", interface!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host.*\"}-node_memory_MemFree_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host.*\"}-node_memory_MemFree_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}