
global:
  scrape_interval:     5s 

# Alerting section
{% if groups['prometheus_alertmanager'] | length  == 1 and deploy_prometheus_alertmanager %}
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      {% for host in groups['prometheus_alertmanager'] -%}
      - {{ host }}:{{prometheus_alertmanager_port}}
      {% endfor %}
{% endif %}

rule_files:
  - /etc/prometheus/*.yaml
  
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:{{prometheus_port}}

{% for host_group in groups -%}
{% if host_group.startswith('agents') %} 
  - job_name: {{ host_group }}
    static_configs:
    - targets: 
{% for host in groups[host_group] -%}
{% if hostvars[host]['deploy_node_exporter'] %}
      - {{ host }}:{{node_exporter_port}}
{% endif -%} 
{% if hostvars[host]['deploy_pcm'] %}
      - {{ host }}:{{pcm_port}}
{% endif -%}
{% if hostvars[host]['deploy_collectd'] %}
      - {{ host }}:{{collectd_port}}
{% endif -%}
{% endfor %}
{% endif %}
{% endfor %}

# Please put you extra exporter configuration here:
