#jinja2:variable_start_string:'[%', variable_end_string:'%]', trim_blocks: False

groups:
- name: prometheus-ne-memory
  rules:
    - alert: high-memory-usage
      expr: 100-((100 / node_memory_MemTotal_bytes * node_memory_MemAvailable_bytes)) > 80
      annotations:
        summary: "System memory usage is higher than 85 % on {{ $labels.instance }}."
        description: "The memory usage is by {{ printf \"%.2f\" $value }} %. Please check the system to avoid system outage."

