
# Grafana Dashboard
grafana_http_port: 3000
grafana_admin_password: 'Suse1234'

# Prometheus
prometheus_port: 9090
prometheus_args:
  - storage.tsdb.retention.time=40d 
  - web.enable-lifecycle
  - web.listen-address=:{{prometheus_port}}

# Prometheus Alertmanager 
prometheus_alertmanager_port: 9093
prometheus_alertmanager_args:
  - web.listen-address=:{{prometheus_alertmanager_port}}

# Node exporter
node_exporter_port: 9100
node_exporter_args:
  - collector.systemd
  - no-collector.mdadm 
  - collector.ksmd 
  - collector.meminfo_numa 
  - no-collector.rapl
  - no-collector.zfs 
  - no-collector.udp_queues 
  - no-collector.softnet
  - no-collector.sockstat 
  - no-collector.nfsd 
  - no-collector.netdev 
  - no-collector.infiniband 
  - no-collector.arp
  - web.listen-address=:{{node_exporter_port}}
  
# Loki 
loki_port: 3100

# Promtail
promtail_port: 9080

# Collectd: Set port
collectd_port: 9103

# Collectd: IP address target
ping_target: 192.168.1.163    # Please change this IP to a valid one

# pcm: set port
pcm_port: 9738
pcm_args:
  - p {{pcm_port}}

