---

- name: Additional facts
  ansible.builtin.include_tasks:
    ../../configuration/tasks/gathering-facts.yaml

- name: Grafana deployment
  ansible.builtin.include_tasks:
    ./grafana.yaml

- name: Grafana Dashboards
  ansible.builtin.include_tasks:
    ./dashboards.yaml
  when: deploy_grafana_dashboards  