#jinja2:variable_start_string:'[%', variable_end_string:'%]', trim_blocks: False

# !! Attention !! Please change the config to you needs.

global:
 resolve_timeout: 15s
 smtp_from: "mylab@work.home"

route:
  group_by: ['alert']
  group_wait: 20s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'mailserver'

receivers:
  - name: 'mailserver'
    email_configs:
      - smarthost: 192.168.1.72:25
        to: 'info@work.home'
        send_resolved: true
        require_tls: false




