#jinja2:variable_start_string:'[%', variable_end_string:'%]', trim_blocks: False

# !! Attention !! Please change the config to you needs.
# For detail about all possible parameter please see: https://prometheus.io/docs/alerting/latest/configuration/

global:
 resolve_timeout: 15s

route:
  group_by: ['alert']
  group_wait: 20s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'mailserver'

receivers:
  - name: 'mailserver'
      email_configs:
      - smarthost: 'smtp.example.com:587'
        auth_username: '<your email id here>'
        auth_password: "<your app password here>"
        from: '<your email id here>'
        to: '<receiver's email id here>'
        headers:
          subject: 'Prometheus Mail Alerts'




