---

# Deploy collectd
- block:

  # If firewall is running open the needed port.
  - name: Collectd - Firewall add port while online
    ansible.posix.firewalld:
      port: "{{collectd_port}}/tcp"
      permanent: true
      state: enabled
      immediate: true
    when:
      - ansible_facts.services["firewalld.service"].state == "running"

  - name: Collectd - Install package
    community.general.zypper:
      name: collectd
      state: latest

  - name: Collectd - Install plugins package
    community.general.zypper:
      name: collectd-plugins-all
      state: latest

  - name: Collectd - Create systemd overwrite directory
    ansible.builtin.file:
      path: /etc/systemd/system/collectd.service.d
      state: directory

  - name: Collectd - Create systemd overwrite file
    ansible.builtin.template:
      src: collectd_systemd_overwrite_file.conf
      dest: /etc/systemd/system/collectd.service.d/override.conf
      mode: "0644"
    register: collectd_overwrite_file_conf

  - name: Collectd - Create config file 
    ansible.builtin.template:
      src: collectd.conf
      dest: /etc/collectd.conf
      mode: "0644"
    register: collectd_config_file_conf

  - name: Collectd - Restart service
    ansible.builtin.service:
      name: collectd.service
      state: restarted 
      enabled: true
    when: 
      - collectd_overwrite_file_conf.changed or collectd_config_file_conf.changed or    
        ansible_facts.services["collectd.service"].state != "running"  

  when: deploy_prometheus_server and (groups['prometheus_server'] | length  == 1) and deploy_collectd


# Don't deploy collectd, remove package and disable port 
- block:

  - name: Collectd - Remove plugins package
    community.general.zypper:
      name: collectd-plugins-all
      state: absent

  - name: Collectd - Remove package
    community.general.zypper:
      name: collectd
      state: absent
 
  - name: Collectd - Remove systemd overwrite file
    ansible.builtin.file:
      path: /etc/systemd/system/collectd.service.d/override.conf
      state: absent
    when: cleanup_config

  - name: Collectd - Remove systemd overwrite directory
    ansible.builtin.file:
      path: /etc/systemd/system/collectd.service.d
      state: absent
    when: cleanup_config   

  - name: Collectd - Remove config file
    ansible.builtin.file:
      path: /etc/collectd.conf
      state: absent
    when: cleanup_config  
   

  # If firewall is not running but installed we have to disable the ports without "immediate:".
  - name: Collectd - Firewall remove port while offline
    ansible.posix.firewalld:
      port: "{{collectd_port}}/tcp"
      permanent: true
      offline: true
      state: disabled
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state != "running"

  # If firewall is running "immediate:" will be used to disable the port immediately.
  - name: Collectd - Firewall remove port while online
    ansible.posix.firewalld:
      port: "{{collectd_port}}/tcp"
      permanent: true
      immediate: true
      state: disabled
    when:
      - ansible_facts.services["firewalld.service"].state == "running"


  when: not deploy_prometheus_server or (groups['prometheus_server'] | length  == 0) or not deploy_collectd

