---

# Deploy node_exporter
- block:

  - name: Firewall permit traffic for  node-exporter port
    ansible.posix.firewalld:
      port: "{{node_exporter_port}}/tcp"
      permanent: true
      state: enabled
      immediate: true
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state == "running"

  - name: Install prometheus-node_exporter
    community.general.zypper:
      name: golang-github-prometheus-node_exporter
      state: latest

  - name: Create prometheus-node_exporter sysconfig file
    ansible.builtin.template:
      src: sysconfig-prometheus-node_exporter
      dest: /etc/sysconfig/prometheus-node_exporter
      mode: "0644"
    register: prometheus_node_exporter_sysconfig_conf  

  - name: Restart prometheus-node_exporter
    ansible.builtin.service:
      name: prometheus-node_exporter.service
      enabled: true
      state: restarted
    when:
      - prometheus_node_exporter_sysconfig_conf.changed or
        ansible_facts.services["prometheus-node_exporter.service"].state != "running"  

  when: deploy_prometheus_server and (groups['prometheus_server'] | length  == 1) and deploy_node_exporter


# Don't deploy node_exporter, stop service and disable port
- block:

  - name: Stop prometheus-node_exporter
    ansible.builtin.service:
      name: prometheus-node_exporter.service
      enabled: false
      state: stopped
    when: "'golang-github-prometheus-node_exporter' in ansible_facts.packages"  

  # Please note that "immediate:" is not set to disable the firewall rule.
  # This is needed to disable the port also on a stopped firewalld.
  - name: Firewall disable collectd port
    ansible.posix.firewalld:
      port: "{{node_exporter_port}}/tcp"
      permanent: true
      offline: true
      state: disabled
    when:
      - "'firewalld' in ansible_facts.packages"

  when: not deploy_prometheus_server or (groups['prometheus_server'] | length  == 0) or not deploy_node_exporter





