---

# Deploy Promtail
- block: 
    
  - name: Promtail - Firewall permit traffic for Promtail ports
    ansible.posix.firewalld:
      port: "{{promtail_port}}/tcp"
      permanent: true
      state: enabled
      immediate: true
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state == "running"

  - name: Promtail - Install package
    community.general.zypper:
      name: promtail
      state: latest

  - name: Promtail - Create config file
    ansible.builtin.template:
      src: promtail.yaml
      dest: /etc/loki/promtail.yaml
      mode: "0644"
    register: promtail_conf  

  - name: Promtail - Restart service
    ansible.builtin.service:
      name: promtail.service
      enabled: true
      state: restarted
    when:
      - promtail_conf.changed or
        ansible_facts.services["promtail.service"].state != "running"  

  when: deploy_loki_server and (groups['loki_server'] | length  == 1) and deploy_promtail



# Don't deploy promtail, remove package and disable port 
- block:

  - name: Promtail - Remove config files 
    ansible.builtin.file:
      path: /etc/loki/promtail.yaml
      state: absent
    when: cleanup_config

  # If firewall is not running but installed we have to disable the ports without "immediate:".
  - name: Promtail - Firewall remove port while offline
    ansible.posix.firewalld:
      port: "{{promtail_port}}/tcp"
      permanent: true
      offline: true
      state: disabled
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state != "running"

  # If firewall is running "immediate:" will be used to disable the port immediately.
  - name: Promtail - Firewall remove port while online
    ansible.posix.firewalld:
      port: "{{promtail_port}}/tcp"
      permanent: true
      immediate: true
      state: disabled
    when:
      - ansible_facts.services["firewalld.service"].state == "running"
      

  when: not deploy_loki_server or (groups['loki_server'] | length  == 0) or not deploy_promtail
  
  