
global:
  scrape_interval:     5s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      {% for host in groups['prometheus-alertmanager'] -%}
      - {{ host }}:{{prometheus_alertmanager_port}}
      {% endfor %}

rule_files:
  - /etc/prometheus/rules.yaml
  
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:{{prometheus_port}}

  - job_name: node-exporter
    static_configs:
    - targets:
      {% for host in groups['monitoring-agents'] -%}
      - {{ host }}:{{node_exporter_port}} 
      {% endfor %}


  - job_name: collectd
    static_configs:
    - targets:
       {% for host in groups['monitoring-agents'] -%}
      - {{ host }}:{{collectd_port}} 
      {% endfor %}


  - job_name: pcm
    static_configs:
    - targets:
       {% for host in groups['monitoring-agents'] -%}
      - {{ host }}:{{pcm_port}} 
      {% endfor %}
