---

# Deploy Prometheus Server
- block:

  # If firewall is running open the needed port.
  - name: Prometheus Server - Firewall add port while online
    ansible.posix.firewalld:
      port: "{{prometheus_port}}/tcp"
      permanent: true
      state: enabled
      immediate: true
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state == "running"

  - name: Prometheus Server - Install package
    community.general.zypper:
      name: golang-github-prometheus-prometheus
      state: latest

  - name: Prometheus Server - Create sysconfig file
    ansible.builtin.template:
      src: sysconfig-prometheus
      dest: /etc/sysconfig/prometheus
      mode: "0644"
    register: prometheus_sysconfig_conf
    
  - name: Prometheus Server - Create config file
    ansible.builtin.template:
      src: prometheus.yml
      dest: /etc/prometheus/prometheus.yml
      mode: "0644"
    register: prometheus_conf

  - name: Prometheus Server - Create a rules directory
    ansible.builtin.file:
      path:  /etc/prometheus/rules/
      state: directory

  - name: Prometheus Server - Create rule file
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/prometheus/rules/{{ item | basename }}
      mode: "0644"
    with_fileglob:
      - templates/rules/*.yaml
    register: prometheus_rules_conf

  - name: Prometheus Server - Restart service
    ansible.builtin.service:
      name: prometheus.service
      state: restarted 
      enabled: true
    when: 
      - prometheus_sysconfig_conf.changed or prometheus_conf.changed or prometheus_rules_conf.changed or     
        ansible_facts.services["prometheus.service"].state != "running"  

  when: deploy_prometheus_server and (groups['prometheus_server'] | length  == 1) 


# Don't deploy Prometheus Server, stop service and disable port  
- block:

  - name: Prometheus Server - Remove package
    community.general.zypper:
      name: golang-github-prometheus-prometheus
      state: absent

  - name: Prometheus Server - Remove config files 
    ansible.builtin.file:
      path: /etc/prometheus/prometheus.yml
      state: absent
    when: cleanup_config 

  - name: Prometheus Server - Remove rules 
    ansible.builtin.file:
      path: /etc/prometheus/rules/
      state: absent
    when: cleanup_config



  # If firewall is not running but installed we have to disable the ports without "immediate:".
  - name: Prometheus Server - Firewall remove port while offline
    ansible.posix.firewalld:
      port: "{{prometheus_port}}/tcp"
      permanent: true
      offline: true
      state: disabled
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state != "running"

  # If firewall is running "immediate:" will be used to disable the port immediately.
  - name: Prometheus Server - Firewall remove port while online
    ansible.posix.firewalld:
      port: "{{prometheus_port}}/tcp"
      permanent: true
      immediate: true
      state: disabled
    when:
      - ansible_facts.services["firewalld.service"].state == "running"


  when: not deploy_prometheus_server or (groups['prometheus_server'] | length  == 0)

