---

# Deploy Loki
- block:

# If firewall is running open the needed port.
  - name: Loki - Firewall add port while online
    ansible.posix.firewalld:
      port: "{{loki_port}}/tcp"
      permanent: true
      state: enabled
      immediate: true
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state == "running"

  - name: Loki - Install package
    community.general.zypper:
      name: loki
      state: latest

  - name: Loki - Create config file
    ansible.builtin.template:
      src: loki.yaml
      dest: /etc/loki/loki.yaml
      owner: loki
      mode: "0644"
    register: loki_conf  

  - name: Loki - Create rules directory
    ansible.builtin.file:
      path: /etc/loki/rules
      owner: loki
      group: loki
      mode: '0644'
      state: directory
    register: loki_rules_conf  

  - name: Loki - Restart service
    ansible.builtin.service:
      name: loki.service
      enabled: true
      state: restarted
    when:
      - loki_conf.changed or loki_rules_conf.changed or
        ansible_facts.services["loki.service"].state != "running"  

  when: deploy_loki_server and (groups['loki_server'] | length  == 1)        


# Don't deploy Loki, stop service and disable port 
- block:

  - name: Loki - Remove package
    community.general.zypper:
      name: loki
      state: absent

  - name: Loki - Remove config file
    ansible.builtin.file:
      path: /etc/loki/loki.yaml
      state: absent
    when: cleanup_config  

  - name: Loki - Remove rule directory
    ansible.builtin.file:
      path: /etc/loki/rules/
      state: absent
    when: cleanup_config

  # If firewall is not running but installed we have to disable the ports without "immediate:".
  - name: Loki - Firewall remove port while offline
    ansible.posix.firewalld:
      port: "{{loki_port}}/tcp"
      permanent: true
      offline: true
      state: disabled
    when:
      - "'firewalld' in ansible_facts.packages"
      - ansible_facts.services["firewalld.service"].state != "running"

  # If firewall is running "immediate:" will be used to disable the port immediately.
  - name: Loki - Firewall remove port while online
    ansible.posix.firewalld:
      port: "{{loki_port}}/tcp"
      permanent: true
      immediate: true
      state: disabled
    when:
      - ansible_facts.services["firewalld.service"].state == "running"
  

  when: not deploy_loki_server or (groups['loki_server'] | length  == 0)      