server:
  http_listen_port: {{promtail_port}}
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
 - url: http://{% for host in groups['loki_server'] -%}{{ host }}{% endfor %}:{{loki_port}}/loki/api/v1/push


scrape_configs:

- job_name: journal
  journal:
    max_age: 24h
    labels:
      inventory_hostname: {{ inventory_hostname }}
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'

    - source_labels: ['__journal__hostname']
      target_label: 'hostname'

    - source_labels: ['__journal__kernel_device']
      target_label: 'kernel_device'

    - source_labels: ['__journal__priority']
      target_label: 'prio'



